name: Weekly CI

on:
  schedule:
    - cron: "0 0 * * 1" # every monday at 00:00
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  weekly-ci:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings -Cdebuginfo=0
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@beta
        with:
          components: clippy
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: clippy all features
        run: cargo clippy --workspace --all-features --all-targets -- -D warnings

      - name: Create Issue if clippy failed
        if: ${{ failure() }}
        uses: dacbd/create-issue-action@v1
        with:
          token: ${{ github.token }}
          title: beta clippy failed
          body: |
            Failed Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
